### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by ManjotS** [creatorKoo/bitwarden-iterm-helper#2]
Awesome tool. I installed via brew and got this:

```$ bw login
/usr/local/Cellar/bitwarden-cli/2023.10.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);
                        ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/usr/local/Cellar/bitwarden-cli/2023.10.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)```

**Comment by creatorKoo** [comment]
Hi @ManjotS !
Thanks for reporting bug.
Can you tell me which command was running an error?
